# 18 - Numpy, Pandas, Matplotlib

- [ ] Numpy
- [ ] Pandas
- [ ] Matplotlib
- [ ] Seaborn 

## Numpy

Numpy е библиотека създадена за работа с масиви. Масивите са едномерни, двумерни и т.н. Масивите са еднотипни, т.е. всички елементи в масива трябва да са от един и същи тип. Масивите са с фиксиран размер, т.е. не може да се добавят или премахват елементи от масива. Масивите са с фиксиран тип, т.е. всички елементи в масива трябва да са от един и същи тип. Масивите са с фиксиран размер, т.е. не може да се добавят или премахват елементи от масива.

In [3]:
!pip install numpy

Едни от важните характеристики на масивите са:
- shape - размер на масива
- dtype - тип на елементите в масива
- ndim - брой измерения на масива
- size - общ брой елементи в масива

In [31]:
def display_numpy_array_info(arr):    
    print(f'{arr=}')
    print(f'{arr.shape=}')
    print(f'{arr.dtype=}')
    print(f'{arr.ndim=}')
    print(f'{arr.size=}')
    print('')

Можем да създадем масив от списък, с помощта на функцията `array`.

In [25]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

display_numpy_array_info(arr)

arr=array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])
arr.shape=(2, 5)
arr.dtype=dtype('int64')
arr.ndim=2
arr.size=10



Можем да зададем типа на елементите в масива с помощта на параметъра `dtype`.

In [26]:
import numpy as np

arr = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=np.float32)

display_numpy_array_info(arr)

arr=array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=float32)
arr.shape=(5,)
arr.dtype=dtype('float32')
arr.ndim=1
arr.size=5



С помощта на функцията `arange` можем да създадем масив с равномерни елементи от start до end със стъпка step.

In [27]:
import numpy as np

arr1 = np.arange(1, 10, 2)
arr2 = np.arange(2, 10, 1)

display_numpy_array_info(arr1)
display_numpy_array_info(arr2)

arr=array([1, 3, 5, 7, 9])
arr.shape=(5,)
arr.dtype=dtype('int64')
arr.ndim=1
arr.size=5

arr=array([2, 3, 4, 5, 6, 7, 8, 9])
arr.shape=(8,)
arr.dtype=dtype('int64')
arr.ndim=1
arr.size=8



Можем да създадем масив от нули или единици, с помощта на функциите `zeros` и `ones`.

In [29]:
import numpy as np

zeros = np.zeros((3, 4))
ones = np.ones((2, 3, 4), dtype=np.int16)

display_numpy_array_info(zeros)
display_numpy_array_info(ones)

arr=array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])
arr.shape=(3, 4)
arr.dtype=dtype('float64')
arr.ndim=2
arr.size=12

arr=array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)
arr.shape=(2, 3, 4)
arr.dtype=dtype('int16')
arr.ndim=3
arr.size=24



С метода `random` можем да създадем масив със случайни числа в интервала от 0 до 1 с размери rows и cols.

In [5]:
import numpy as np

random = np.random.random((2, 3))

display_numpy_array_info(random)

arr=array([[0.85258647, 0.87437575, 0.04258029],
       [0.06627148, 0.24665089, 0.52177255]])
arr.shape=(2, 3)
arr.dtype=dtype('float64')
arr.ndim=2
arr.size=6



С метода `reshape` можем да преоразмерим масива.

In [30]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
display_numpy_array_info(arr)

arr1 = arr.reshape(3, 2)
display_numpy_array_info(arr1)

arr=array([[1, 2, 3],
       [4, 5, 6]])
arr.shape=(2, 3)
arr.dtype=dtype('int64')
arr.ndim=2
arr.size=6

arr=array([[1, 2],
       [3, 4],
       [5, 6]])
arr.shape=(3, 2)
arr.dtype=dtype('int64')
arr.ndim=2
arr.size=6



Numpy поддържа и някои математически операции между масиви.

In [1]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([5, 7, 8])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)
print(a / 10)
print(a > 15)

[15 27 38]
[ 5 13 22]
[ 50 140 240]
[2.         2.85714286 3.75      ]
[100 400 900]
[1. 2. 3.]
[False  True  True]


In [19]:
import numpy as np 

a = np.random.random((2, 3)) * 100

print(a)
print(a.sum())
print(a.min())
print(a.max())
print(a.std())

[[71.34135627  0.25907481 89.56057185]
 [94.61009345 24.91787537 77.29307812]]
357.98204987140775
0.2590748147073829
94.61009345054515
34.87696903183212


In [18]:
import numpy as np

b = np.arange(1, 10)
print(b)
print(np.exp(b))
print(np.sqrt(b))

[1 2 3 4 5 6 7 8 9]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


Numpy поддържа и сумиране на масиви, по даден ред или колона.

In [20]:
import numpy as np

c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print(c.sum(axis=0))
print(c.sum(axis=1))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


Една особеност на Numpy е индексацията. Ако имаме двумерен масив, и искаме да достъпим елемента на 0-лев ред и 1-ви колона, то индексацията е следната `arr[0, 1]`. Ако използваме само един индекс, то той се отнася за редовете. Т.е. `arr[0]` ще ни върне първия ред от масива. Ако искаме да изберем цял ред, колона или която и да е друга размерност, можем да използваме `:`. Т.е. `arr[:, 1]` ще ни върне всички редове от втората колона.

In [26]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)

print(a)

print(f'{a[0, 1]=}')
print(f'{a[1, :]=}')
print(f'{a[:, 2]=}')

a[0, 1] = 1
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a[0, 1]=2
a[1, :]=array([5, 6, 7, 8])
a[:, 2]=array([ 3,  7, 11])
[[ 1  1  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Освен с числа, можем да индексираме и с булеви масиви. Можем да подадем масив от булеви стойности - ако стойността на даден елемент е `True`, то той ще бъде включен в резултата, а ако е `False`, то няма да бъде включен.

In [39]:
import numpy as np

a = np.arange(1, 10)
print(a)

even_mask = a % 2 == 0
print(a[even_mask])
print(a[a % 2 == 0])

[1 2 3 4 5 6 7 8 9]
[2 4 6 8]
[2 4 6 8]


Numpy поддържа три вида копиране - никакво, плитко и дълбоко. 

Когато извикаме `arr2 = arr1`, то това е никакво копиране. Т.е. `arr2` е просто друго име на `arr1`. Ако променим елемента на `arr2`, то той ще се промени и в `arr1`.

Когато извикаме `arr3 = arr.view()`, ще се създаде нов обект, но данните няма да се копират.

Когато извикаме `arr4 = arr.copy()`, ще се създаде нов обект, с копие на данните.

In [28]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
print(a)

b = a
c = a.view()
d = a.copy()

a[0, 0] = 100

print(b)
print(c)
print(d)

print(b is a)
print(c is a)
print(d is a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
True
False
False


Numpy ни позволява да прилагаме функции към нашите масиви. Например, можем да приложим функцията `sqrt` към всеки елемент на масива.

In [32]:
import numpy as np

def square(x):
    return x ** 2

a = np.arange(1, 10)

print(a)

b = square(a)
display_numpy_array_info(b)

[1 2 3 4 5 6 7 8 9]
arr=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])
arr.shape=(9,)
arr.dtype=dtype('int64')
arr.ndim=1
arr.size=9



## Pandas

## Matplotlib

## Seaborne